### ISSUE TITLE
Unauthenticated. HTTP 401 Error.

### ISSUE THREAD

**Issue by abazad** [tooleks/photo-blog#263]
when i try to login in http://localhost:8080/sign-in, got error Unauthenticated. HTTP 401 Error at red alertbox.

all services and mysql up.

**Comment by tooleks** [comment]
Thanks. Will check on a fresh install.

**Comment by tooleks** [comment]
To fix that, replace `OAUTH_CLIENT_ID=4` with `OAUTH_CLIENT_ID=2` in the `./app/.env` file.
Regarding new installs, I have prepared a fix in the commit https://github.com/tooleks/photo-blog/commit/1b2e557f3dfc1760f1a82b994f5c036ccad17249.

**Comment by abazad** [comment]
thank you so much :)
