### ISSUE TITLE
Instructions with no Docker?

### ISSUE THREAD

**Issue by bartonhammond** [tooleks/photo-blog#286]
Beautiful project!  
Do you have setup instruction that don't use Docker?  I'd much rather install everything locally.

**Comment by tooleks** [comment]
Thanks.
I think that a good point. The problem that I see now is that it may be hard to cover all possible edge cases of configuration for all platforms. With Docker, you'll probably not have any issues like this. Anyway, I think, I'll try to do some sort of high-level description in the nearest future at least for Linux environment. That would be a starting point.
