### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation...

### ISSUE THREAD

**Issue by HINW** [tooleks/photo-blog#308]
Hi,

When uploading photo getting this error:

"SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION photo_blog.ASTEXT does not exist (SQL: select `locations`.*, ASTEXT(locations.coordinates) AS coordinates from `locations` where `locations`.`id` in ())
HTTP 500 Error."

Tried also with postgresql, same result:

"LSTATE[42883]: Undefined function: 7 ERROR: function astext(point) does not exist LINE 1: select "locations".*, ASTEXT(locations.coordinates) AS coord... ^ HINT: No function matches the given name and argument types. You might need to add explicit type casts. (SQL: select "locations".*, ASTEXT(locations.coordinates) AS coordinates from "locations" where "locations"."id" in ())
HTTP 500 Error."

**Comment by tooleks** [comment]
Hey @HINW, what database and version do you use?

**Comment by HINW** [comment]
Hi and thanks for reply! I have:

mysql  Ver 8.0.13 for Linux on x86_64 (MySQL Community Server - GPL)

and

psql (PostgreSQL) 10.5 (Ubuntu 10.5-0ubuntu0.18.04)

Regards,
Henrik

**Comment by tooleks** [comment]
I've prepared a fix in `development` branch. Could you pull the changes (`development` branch) and verify that issue no longer exist?

**Comment by tooleks** [comment]
I've prepared a fix in `development` branch.

https://github.com/tooleks/photo-blog/blob/65360c3b77d3e86ec2de2d89bb9f8a88c33a2b82/app/src/app/Models/Builders/LocationBuilder.php#L29

Could you pull the changes from `development` branch and verify that issue no longer exist for you?

**Comment by HINW** [comment]
Hi, now I getting "Invalid response type" the record in DB is made and file got uploaded into "storage/app/public/photos" directory. Henrik

**Comment by tooleks** [comment]
Could you send me an output of `make app-logs` command?

**Comment by tooleks** [comment]
Could you send me logs from `./app/storage/logs/laravel.log`?

**Comment by HINW** [comment]
Here it is, I juste removed my email from error log. 

Laravel development server started: <http://127.0.0.1:8000>
[Wed Oct 24 22:42:43 2018] 127.0.0.1:52228 [200]: /css/app.css
[Wed Oct 24 22:42:43 2018] 127.0.0.1:52230 [200]: /js/app.js
[2018-10-24 20:42:56] local.ERROR: Class 'App\Models\Builders\LocationBuilder' not found {"userId":1,"email":"my_email","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'App\\Models\\Builders\\LocationBuilder' not found at /home/henrik/Development/Apps/Laravel/photo-blog-master/app/src/app/Models/Location.php:75)
[stacktrace]
#0 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(952): App\\Models\\Location->newEloquentBuilder(Object(Illuminate\\Database\\Query\\Builder))
#1 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(988): Illuminate\\Database\\Eloquent\\Model->newModelQuery()
#2 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(941): Illuminate\\Database\\Eloquent\\Model->newQueryWithoutScopes()
#3 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/src/app/Models/Location.php(83): Illuminate\\Database\\Eloquent\\Model->newQuery()
#4 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php(151): App\\Models\\Location->newQuery()
#5 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/src/app/Models/Photo.php(91): Illuminate\\Database\\Eloquent\\Model->belongsTo('App\\\\Models\\\\Loca...', 'location_id')
#6 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(581): App\\Models\\Photo->location()
#7 [internal function]: Illuminate\\Database\\Eloquent\\Builder->Illuminate\\Database\\Eloquent\\{closure}()
#8 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php(90): call_user_func(Object(Closure))
#9 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(585): Illuminate\\Database\\Eloquent\\Relations\\Relation::noConstraints(Object(Closure))
#10 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(553): Illuminate\\Database\\Eloquent\\Builder->getRelation('location')
#11 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(533): Illuminate\\Database\\Eloquent\\Builder->eagerLoadRelation(Array, 'location', Object(Closure))
#12 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(490): Illuminate\\Database\\Eloquent\\Builder->eagerLoadRelations(Array)
#13 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/src/app/Managers/Photo/PhotoManager.php(155): Illuminate\\Database\\Eloquent\\Model->load('location', 'exif', 'thumbnails')
#14 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/src/api/V1/Http/Controllers/PhotosController.php(97): App\\Managers\\Photo\\PhotoManager->create(Array)
#15 [internal function]: Api\\V1\\Http\\Controllers\\PhotosController->create(Object(Illuminate\\Http\\Request))
#16 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#17 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('create', Array)
#18 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Api\\V1\\Http\\Controllers\\PhotosController), 'create')
#19 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#20 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(679): Illuminate\\Routing\\Route->run()
#21 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authorize.php(45): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#23 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Auth\\Middleware\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'create-resource', 'App\\\\Models\\\\Phot...')
#24 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authorize.php(45): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#26 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Auth\\Middleware\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'access-administ...')
#27 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#29 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#32 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'api')
#33 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/src/api/V1/Http/Middleware/JsonApiResponses.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#35 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Api\\V1\\Http\\Middleware\\JsonApiResponses->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/src/api/V1/Http/Middleware/CookieOAuthAuthorizer.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#38 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Api\\V1\\Http\\Middleware\\CookieOAuthAuthorizer->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#41 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#42 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#43 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(622): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#44 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(611): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#45 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#46 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#47 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/src/app/Http/Middleware/Prerender.php(109): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#48 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): App\\Http\\Middleware\\Prerender->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#51 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#54 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#57 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#59 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#60 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#62 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/src/app/Http/Middleware/CorsHeaders.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#63 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): App\\Http\\Middleware\\CorsHeaders->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#64 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#65 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#66 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#67 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#68 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#69 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#70 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#71 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#72 /home/henrik/Development/Apps/Laravel/photo-blog-master/app/server.php(21): require_once('/home/henrik/De...')
#73 {main}
"}

**Comment by tooleks** [comment]
Ok, at least there is no longer the database issue. Now it looks like something is with the class autoloader. I would probably run `composer install && composer dump-autoload` to re-install composer dependencies and to force a new dump of the autoloader files. Please, let me know if it helps.

**Comment by tooleks** [comment]
Ok, at least it is no longer the database issue. Now it looks like something is with the class autoloader. I would probably run `composer install && composer dump-autoload` to re-install composer dependencies and to force a new dump of the autoloader files. Please, let me know if it helps.

**Comment by tooleks** [comment]
Ok, at least it is no longer the database issue. Now it looks like something wrong with the class autoloader. What I would probably do is to run `composer install && composer dump-autoload` command to re-install composer dependencies and to force a new dump of the autoloader files. Please, try it and let me know if it helps.

**Comment by tooleks** [comment]
Ok, that's cool.

> But I found a new bug: photos get uploaded to the server before user hit button "Save".

Yep, that's an expected behavior. `Photo` entity created each time when you upload a new photo, but `Post` entity created only once when you hit the "Save" button. There is also a background job that removes unattached photos. Definitely, that could be improved but it requires additional work and it is not in a priority right now.

> It would be useful feature to be able to grab current location when uploading photos. On pageload and/or by button "set current location" or something like that, probably by both methods.

Yeah, great request! I think I'll implement this when I'll have a time, like a week or two.

Thanks for finding the issue!

**Comment by tooleks** [comment]
>

**Comment by tooleks** [comment]
@HINW Merged geolocation feature from https://github.com/tooleks/photo-blog/pull/310/commits/54a034844554a913510354215be1f7249f967171 to `master` branch.
